# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/article/1
Accept: application/json

###

GET http://127.0.0.1:8000/article/list?page=1&size=10
Accept: application/json
Content-Type: application/json

###

POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "password"
}

###

GET http://127.0.0.1:8000/user/list
Accept: application/json

###

GET http://127.0.0.1:8000/api/user/test/sendmail?email=langyawuhen008@126.com
Accept: application/json